//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.29 at 11:59:17 AM CET 
//


package com.generatedClasses.presentation;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.generatedClasses.presentation package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.generatedClasses.presentation
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DeletePPTResponse }
     * 
     */
    public DeletePPTResponse createDeletePPTResponse() {
        return new DeletePPTResponse();
    }

    /**
     * Create an instance of {@link CreateOrUpdatePPTResponse }
     * 
     */
    public CreateOrUpdatePPTResponse createCreateOrUpdatePPTResponse() {
        return new CreateOrUpdatePPTResponse();
    }

    /**
     * Create an instance of {@link DeletePPTResponse.Response }
     * 
     */
    public DeletePPTResponse.Response createDeletePPTResponseResponse() {
        return new DeletePPTResponse.Response();
    }

    /**
     * Create an instance of {@link CreateOrUpdatePPTResponse.Response }
     * 
     */
    public CreateOrUpdatePPTResponse.Response createCreateOrUpdatePPTResponseResponse() {
        return new CreateOrUpdatePPTResponse.Response();
    }

    /**
     * Create an instance of {@link CreateOrUpdatePPTRequest }
     * 
     */
    public CreateOrUpdatePPTRequest createCreateOrUpdatePPTRequest() {
        return new CreateOrUpdatePPTRequest();
    }

    /**
     * Create an instance of {@link DocumentPPT }
     * 
     */
    public DocumentPPT createDocumentPPT() {
        return new DocumentPPT();
    }

    /**
     * Create an instance of {@link DeletePPTRequest }
     * 
     */
    public DeletePPTRequest createDeletePPTRequest() {
        return new DeletePPTRequest();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

}
